import type { FishSpecies, PlantSpecies, TankSize, Disease, Article, CompatibilityResult } from '@/types';

// ============================================================
// In production, these functions read from JSON data files
// in /src/data/ that are generated by build scripts from the
// master database. For now, they export stub functions that
// will be populated as data is added.
// ============================================================

const DATA_DIR = '@/data';

// ============================================================
// FISH
// ============================================================
export async function getAllFish(): Promise<FishSpecies[]> {
  try {
    const data = await import('@/data/fish.json');
    return data.default as FishSpecies[];
  } catch {
    return [];
  }
}

export async function getFishBySlug(slug: string): Promise<FishSpecies | null> {
  const all = await getAllFish();
  return all.find((f) => f.slug === slug) ?? null;
}

export async function getFishByCategory(category: 'freshwater' | 'saltwater'): Promise<FishSpecies[]> {
  const all = await getAllFish();
  return all.filter((f) => f.category === category);
}

export async function getFishSlugs(): Promise<string[]> {
  const all = await getAllFish();
  return all.map((f) => f.slug);
}

// ============================================================
// PLANTS
// ============================================================
export async function getAllPlants(): Promise<PlantSpecies[]> {
  try {
    const data = await import('@/data/plants.json');
    return data.default as PlantSpecies[];
  } catch {
    return [];
  }
}

export async function getPlantBySlug(slug: string): Promise<PlantSpecies | null> {
  const all = await getAllPlants();
  return all.find((p) => p.slug === slug) ?? null;
}

export async function getPlantSlugs(): Promise<string[]> {
  const all = await getAllPlants();
  return all.map((p) => p.slug);
}

// ============================================================
// TANK SIZES
// ============================================================
export async function getAllTankSizes(): Promise<TankSize[]> {
  try {
    const data = await import('@/data/tank-sizes.json');
    return data.default as TankSize[];
  } catch {
    return [];
  }
}

export async function getTankSizeBySlug(slug: string): Promise<TankSize | null> {
  const all = await getAllTankSizes();
  return all.find((t) => t.slug === slug) ?? null;
}

// ============================================================
// DISEASES
// ============================================================
export async function getAllDiseases(): Promise<Disease[]> {
  try {
    const data = await import('@/data/diseases.json');
    return data.default as Disease[];
  } catch {
    return [];
  }
}

export async function getDiseaseBySlug(slug: string): Promise<Disease | null> {
  const all = await getAllDiseases();
  return all.find((d) => d.slug === slug) ?? null;
}

// ============================================================
// COMPATIBILITY
// ============================================================
export async function getCompatibility(fishA: string, fishB: string): Promise<CompatibilityResult | null> {
  try {
    const data = await import('@/data/compatibility.json');
    const matrix = data.default as CompatibilityResult[];
    return (
      matrix.find(
        (c) =>
          (c.fishA === fishA && c.fishB === fishB) ||
          (c.fishA === fishB && c.fishB === fishA)
      ) ?? null
    );
  } catch {
    return null;
  }
}

// ============================================================
// ARTICLES (MDX-based editorial content)
// ============================================================
export async function getAllArticles(): Promise<Article[]> {
  try {
    const data = await import('@/data/articles-index.json');
    return data.default as Article[];
  } catch {
    return [];
  }
}

export async function getArticleBySlug(slug: string): Promise<Article | null> {
  const all = await getAllArticles();
  return all.find((a) => a.slug === slug) ?? null;
}

export async function getArticlesByPillar(pillar: string): Promise<Article[]> {
  const all = await getAllArticles();
  return all.filter((a) => a.pillar === pillar);
}

// ============================================================
// SITEMAP HELPERS
// ============================================================
export async function getAllSitemapUrls(): Promise<{ url: string; lastmod: string; priority: number }[]> {
  const [fish, plants, tankSizes, diseases, articles] = await Promise.all([
    getAllFish(),
    getAllPlants(),
    getAllTankSizes(),
    getAllDiseases(),
    getAllArticles(),
  ]);

  const urls: { url: string; lastmod: string; priority: number }[] = [];
  const now = new Date().toISOString().split('T')[0];

  // Static pages
  urls.push({ url: '/', lastmod: now, priority: 1.0 });
  urls.push({ url: '/calculators/tank-volume', lastmod: now, priority: 0.8 });
  urls.push({ url: '/calculators/stocking', lastmod: now, priority: 0.8 });
  urls.push({ url: '/calculators/heater-size', lastmod: now, priority: 0.8 });

  // Programmatic pages
  fish.forEach((f) => urls.push({ url: `/fish/${f.slug}`, lastmod: now, priority: 0.7 }));
  plants.forEach((p) => urls.push({ url: `/plants/${p.slug}`, lastmod: now, priority: 0.7 }));
  tankSizes.forEach((t) => urls.push({ url: `/tank-sizes/${t.slug}`, lastmod: now, priority: 0.8 }));
  diseases.forEach((d) => urls.push({ url: `/diseases/${d.slug}`, lastmod: now, priority: 0.6 }));

  // Editorial articles
  articles.forEach((a) =>
    urls.push({ url: `/${a.pillar}/${a.slug}`, lastmod: a.updatedAt, priority: 0.8 })
  );

  return urls;
}
